name: tests

on: [push, pull_request]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
        numpy-version: ['1.25.2', '1.26.4', '2.0.2', '2.1.3', '2.2.6', '2.3.2']
        os: [ubuntu-latest]
        exclude:
        - python-version: '3.9'
          numpy-version: '2.1.3'
        - python-version: '3.9'
          numpy-version: '2.2.6'
        - python-version: '3.9'
          numpy-version: '2.3.2'
        - python-version: '3.10'
          numpy-version: '2.3.2'
        - python-version: '3.12'
          numpy-version: '1.25.2'
        - python-version: '3.13'
          numpy-version: '1.25.2'
        - python-version: '3.13'
          numpy-version: '1.26.4'
        - python-version: '3.13'
          numpy-version: '2.0.2'

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
    - name: Set up ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy==${{ matrix.numpy-version }}
        python -m pip install pytest
    - name: Install las
      run: |
        python -m pip install .
    - name: Test with pytest
      run: |
        cd tests
        python -m pytest
